default:
  general:
    apolloPlayground: true
    apolloIntrospection: true
    bcryptHashCostFactor: 12
    urlAdapter: default
  mailProvider:
    id: slackMail # allowed is mailchimp/mailgun
    fromAddress: dev@wepublish.ch # Required for mailchimp/mailgun
    webhookURL: 'https://slack.com/webhookURL'
  OAuthProviders:
    - name: 'google'
      discoverUrl: 'https://accounts.google.com'
      clientId: '617896178757-i6ldn0nni9qtle8o6eu76lv93d78nvfi.apps.googleusercontent.com'
      clientKey: 't267ZLqkV9dacrkPQp_pF-G2'
      redirectUri:
        - 'http://localhost:4000/auth/google'
      scopes:
        - 'openid profile email'
  paymentProviders:
    - type: payrexx # Allowed are stripe_checkout / stripe / payrexx / bexio
      id: payrexx # Required for stripe_checkout / stripe / payrexx /bexio
      name: Payrexx # Required for stripe_checkout / stripe / payrexx /bexio
      offSessionPayments: true # Required for stripe_checkout / stripe / payrexx
      secretKey: secret # Required for stripe_checkout / stripe
      webhookApiKey: secret
      instanceName: name  # Required for payrexx
      instanceAPISecret: secret # Required for payrexx
      psp: # Required for payrexx
        - 0
        - 15
        - 17
        - 2
        - 3
        - 36
      pm: # Required for payrexx
        - 'postfinance_card'
        - 'postfinance_efinance'
        - 'mastercard'
        - 'visa'
        - 'twint'
        - 'invoice'
        - 'paypal'
      vatRate: 8.1 # Required for payrexx
    - type: payrexx-subscription
      id: payrexx-subscription
      name: payrexx-subscription
      webhookEndpointSecret: secret
      instanceName: wepublish-dev
      instanceAPISecret: secret
    - type: bexio
      id: bexio
      name: Bexio
      apiKey: key
      userId: userId
      countryId: country
      invoiceTemplateNewMembership: template1
      invoiceTemplateRenewalMembership: template1
      unitId: 1
      taxId: 2
      accountId: 2
      invoiceTitleNewMembership: invoiceTitleNewMembership
      invoiceTitleRenewalMembership: "invoiceTitleRenewalMembership"
      invoiceMailSubjectNewMembership: "invoiceMailSubjectNewMembership"
      invoiceMailBodyNewMembership: "invoiceMailBodyNewMembership"
      invoiceMailSubjectRenewalMembership: "invoiceMailSubjectRenewalMembership"
      invoiceMailBodyRenewalMembership: "invoiceMailBodyRenewalMembership"
      markInvoiceAsOpen: False
  challenge:
    secret: 'secret'
    validTime: 600
    width: 200
    height: 200
    background: '#ffffff'
    noise: 5
    minValue: 1
    maxValue: 10
    operandAmount: 1
    operandTypes:
      - '+'
      - '-'
    mode: 'formula'
    targetSymbol: '?'
