---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "helm.fullname" . }}-frontend
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "helm.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}-frontend
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm.name" . }}-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helm.name" . }}-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.deployment.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.deployment.imagePullSecret }}
      {{- end }}
      containers:
        - name: {{ include "helm.fullname" . }}
          image: {{ .Values.frontend.image }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "helm.fullname" . }}-env-{{ .Release.Revision }}
            {{- if .Values.frontend.envFromSecretRefName }}
            - secretRef:
                name: {{ .Values.frontend.envFromSecretRefName }}
            {{- end }}
          {{- with .Values.frontend.properties }}
          {{- toYaml . | nindent 10 }}
          {{- end }}


---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-env-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/name: {{ include "helm.fullname" . }}-env-{{ .Release.Revision }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- range $name, $value := merge .Values.frontend.env .Values.deployment.env }}
  {{ $name }}: "{{ $value | b64enc }}"
  {{- end }}
