deployment:
  imagePullPolicy: Always
  imagePullSecret:
  env:
    API_URL: https://api
    FRONTEND_URL: https://front

frontend:
  image: ghcr.io/wepublish/frontend
  env:
  envFromSecretRefName:
  properties: {}
  replicaCount: 1

labels: {}
