name: Deployment

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Authenticate kubectl
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}

      - name: Prepare kubectl
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          cluster_name: production
          location: europe-west6

      - name: Helm Deploy
        uses: 'deliverybot/helm@v1'
        with:
          release: 'dev-app-pr${{ github.event.pull_request.number }}'
          namespace: 'dev'
          helm: helm3
          chart: 'helm/charts/wepublish'
          token: '${{ github.token }}'
          values: |
            deployment:
              image: ${{ inputs.image }}
              imagePullPolicy: Always
              env:
                API_URL: https://api-${{ github.event.pull_request.number }}.dev.wepublish.media
                EDITOR_URL: https://editor-${{ github.event.pull_request.number }}.dev.wepublish.media
                WEBSITE_URL: https://website-${{ github.event.pull_request.number }}.dev.wepublish.media
                MEDIA_SERVER_URL: https://media-${{ github.event.pull_request.number }}.dev.wepublish.media
                NODE_ENV: production
            api:
              env:
                GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/key.json
                DATABASE_URL: 'postgresql://admin:postgres/wepublish-dev?schema=public'
                MEDIA_SERVER_TOKEN: media-token
                JWT_SECRET_KEY: jwt-secret-key
              envFromSecretRefName:
              properties: {}
              replicaCount: 1
            editor:
              env:
                PEER_BY_DEFAULT: "true"
              properties: {}
              replicaCount: 1
            website:
              enabled: true
              env:
                ALLOWED_HOSTS: website-${{ github.event.pull_request.number }}.dev.wepublish.media
              envFromSecretRefName:
              properties: {}
              replicaCount: 1
            labels: {}
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

  notify:
    needs: deployment
    if: ${{ needs.deployment.result == 'success' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Create Deployment Text
        id: deploymentComment
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          cd ./config
          npm ci
          OUTPUT=$(node ./notify-github.js)
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-OUTPUT name=result::$OUTPUT"

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ${{ steps.deploymentComment.outputs.result }}

      - name: Notify Jira
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          cd ./config
          npm ci
          node ./notify-jira.js
