name: Publish master artifacts

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  date_sha_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.image_tag.outputs.tag }}
    steps:
      - id: image_tag
        run: echo "::set-output name=tag::$(date +%s)-${{ github.sha }}"

  setup-frontend-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up matrix
        id: set-matrix
        run: deployment/read_deployment_config.sh '.frontend.staging.deployment' true

  publish_master_docker:
    needs: date_sha_tag
    uses: ./.github/workflows/on-demand-publish-docker-image.yml
    with:
      migration_tags: |
        ghcr.io/wepublish/migration:master-${{ needs.date_sha_tag.outputs.tag }}
        ghcr.io/wepublish/migration:master
        wepublishch/migration:master
      api_tags: |
        ghcr.io/wepublish/api:master-${{ needs.date_sha_tag.outputs.tag }}
        ghcr.io/wepublish/api:master
        wepublishch/api:master
      editor_tags: |
        ghcr.io/wepublish/editor:master-${{ needs.date_sha_tag.outputs.tag }}
        ghcr.io/wepublish/editor:master
        wepublishch/editor:master
      media_tags: |
        ghcr.io/wepublish/media:master-${{ needs.date_sha_tag.outputs.tag }}
        ghcr.io/wepublish/media:master
        wepublishch/media:master
      storybook_tags: |
        ghcr.io/wepublish/storybook:master-${{ needs.date_sha_tag.outputs.tag }}
        ghcr.io/wepublish/storybook:master
        wepublishch/storybook:master
      website_tags: |
        ghcr.io/wepublish/website:master-${{ needs.date_sha_tag.outputs.tag }}
        ghcr.io/wepublish/website:master
        wepublishch/website:master
    secrets: inherit

  publish_docker_frontend_image:
    name: Frontend
    needs: [ setup-frontend-matrix, date_sha_tag, publish_master_docker ]
    if: ${{ needs.helm_deployment.result == 'success' }}
    uses: ./.github/workflows/on-demand-publish-docker-image-frontend.yml
    strategy:
      matrix: ${{fromJson(needs.publish_master_docker.outputs.matrix)}}
    with:
      frontend_project: ${{ matrix.target }}
      api_url: https://api-${{ matrix.target }}.wepublish.dev
      frontend_tags: |
        ghcr.io/wepublish/frontend-${{ matrix.target }}:master-${{ needs.date_sha_tag.outputs.tag }}
    secrets: inherit