name: Deploy production

on:
  push:
    tags:
      - 'deploy_*'

jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.image_tag.outputs.version }}
      project: ${{ steps.image_tag.outputs.project }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: image_tag
        run: ./deployment/get_production_tag.sh ${GITHUB_REF##*/}

  deploy_wepublish_production:
    needs: get-tag
    uses: ./.github/workflows/on-demand-publish-docker-image.yml
    if: ${{ needs.get-tag.result == 'success' }}
    with:
      migration_tags: |
        ghcr.io/wepublish/migration:production-${{ needs.get-tag.outputs.project }}-${{ needs.get-tag.outputs.version }}
      api_tags: |
        ghcr.io/wepublish/api:production-${{ needs.get-tag.outputs.project }}-${{ needs.get-tag.outputs.version }}
      editor_tags: |
        ghcr.io/wepublish/editor:production-${{ needs.get-tag.outputs.project }}-${{ needs.get-tag.outputs.version }}
      media_tags: |
        ghcr.io/wepublish/media:production-${{ needs.get-tag.outputs.project }}-${{ needs.get-tag.outputs.version }}
    secrets: inherit

  deploy_frontend_production:
    name: Frontend
    needs: [ deploy_production, get-tag ]
    if: ${{ needs.deploy_production.result == 'success' }}
    uses: ./.github/workflows/on-demand-publish-docker-image-frontend.yml
    with:
      frontend_project: ${{ needs.get-tag.outputs.project }}
      api_url: https://api-${{ needs.get-tag.outputs.project }}.wepublish.media
      frontend_tags: |
        ghcr.io/wepublish/frontend-${{ needs.get-tag.outputs.project }}:production-${{ needs.get-tag.outputs.version }}
    secrets: inherit